### ISSUE TITLE
Option to add location header information instead of just blocking / passing

### ISSUE THREAD

**Issue by RoboMagus** [PascalMinder/GeoBlock#10]
Comparing this plugin with [ip2location](https://github.com/negasus/traefik-plugin-ip2location) I see the potential for one additional feature here. 
For some subdomains I'd like to outright block requests that me or my users could not be making (e.g. from outside the country), however as some services are approached by various webhooks I would like to be less restrictive for those.

Having the option to add the Client IP country code added to the headers comparable to [ip2location](https://github.com/negasus/traefik-plugin-ip2location) (instead of blocking access) would allow users to handle access control using middlewares for different routers.

I would be tempted to use the other mentioned plugin, however it seems to not be maintained. That, and the configurability of your plugin related to unknown countries and local IPs is not something I would like to give up.

**Comment by PascalMinder** [comment]
Hi @RoboMagus 

Thanks for opening this issue. 

As I understand, you would like to be able to configure the extension based on the subdomain its running on? The new feature would be adding the country code to the request header, if this feature is configured for the current subdomain. Also, the extension should not outright block the request, but if configured to allow it forward it to the next middleware?

**Comment by RoboMagus** [comment]
Hey, I forgot about this issue but I saw I still had it open.

I had been looking for other ways to get Geoblocking to work for my usecase and I ended up using [geoblock by kucjac](https://github.com/kucjac/traefik-plugin-geoblock).

Now my config just contains multiple geoblock middlewares depending on the required blocking for each service:
```yaml
- 'traefik.http.middlewares.nl_only.plugin.geoblock.enabled=true'
- 'traefik.http.middlewares.nl_only.plugin.geoblock.databaseFilePath=/plugins-local/src/github.com/kucjac/traefik-plugin-geoblock/IP2LOCATION-LITE-DB1.IPV6.BIN'
- 'traefik.http.middlewares.nl_only.plugin.geoblock.allowedCountries=NL'
- 'traefik.http.middlewares.nl_only.plugin.geoblock.allowPrivate=true' 

- 'traefik.http.middlewares.geoblock.plugin.geoblock.enabled=true'
- 'traefik.http.middlewares.geoblock.plugin.geoblock.databaseFilePath=/plugins-local/src/github.com/kucjac/traefik-plugin-geoblock/IP2LOCATION-LITE-DB1.IPV6.BIN'
- 'traefik.http.middlewares.geoblock.plugin.geoblock.disallowedCountries=CN,RU'
- 'traefik.http.middlewares.geoblock.plugin.geoblock.allowPrivate=true'
```

Still a bummer that what I've got running now relies on a local database of IP to country mappings, but the basic blocking rules do satisfy my requirements.

Looking back at this, different middleware instanciations of your plugin might have also solved the trick. But I could not find a configuration example for this plugin that allowed me to set it up as such.

**Comment by PascalMinder** [comment]
Did you try the same kind of configuration with my plugin? I think this should also work.

**Comment by PascalMinder** [comment]
In my traefik.yml:
```
experimental:
  localPlugins:
    geoblock:
      moduleName: github.com/PascalMinder/GeoBlock
```

and then for each container:
```
  hello:
    image: containous/whoami
    labels:
      - traefik.enable=true
      - traefik.http.routers.hello.entrypoints=http
      - traefik.http.routers.hello.rule=Host(`hello.localhost`)
      - traefik.http.services.hello.loadbalancer.server.port=80
      - traefik.http.routers.hello.middlewares=is-only
      - traefik.http.middlewares.is-only.plugin.geoblock.allowLocalRequests=false
      - traefik.http.middlewares.is-only.plugin.geoblock.logLocalRequests=true
      - traefik.http.middlewares.is-only.plugin.geoblock.logAllowedRequests=true
      - traefik.http.middlewares.is-only.plugin.geoblock.logApiRequests=true
      - "traefik.http.middlewares.is-only.plugin.geoblock.api=https://get.geojs.io/v1/ip/country/{ip}"
      - traefik.http.middlewares.is-only.plugin.geoblock.cacheSize=15
      - traefik.http.middlewares.is-only.plugin.geoblock.forceMonthlyUpdate=true
      - traefik.http.middlewares.is-only.plugin.geoblock.allowUnknownCountries=false
      - traefik.http.middlewares.is-only.plugin.geoblock.unknownCountryApiResponse=nil
      - traefik.http.middlewares.is-only.plugin.geoblock.countries=IS
```
