### ISSUE TITLE
Plugin manifest error

### ISSUE THREAD

**Issue by ezruneko** [PascalMinder/geoblock#22]
Traefik version: 2.8.1

traefik.yml

```
experimental:
  localPlugins:
    geoblock:
      moduleName: github.com/PascalMinder/GeoBlock
```

Crash with only add this four lines and traefik can't started.

The log error:
```
2022/07/21 08:59:15 traefik.go:80: command traefik error: 1 error occurred:
	* failed to open the plugin manifest plugins-local/src/github.com/PascalMinder/GeoBlock/.traefik.yml: open plugins-local/src/github.com/PascalMinder/GeoBlock/.traefik.yml: no such file or directory
```

**Comment by PascalMinder** [comment]
can you change the line `moduleName: github.com/PascalMinder/GeoBlock` to `moduleName: github.com/PascalMinder/geoblock`?

**Comment by ezruneko** [comment]
Same error
```
2022/07/21 09:22:16 traefik.go:80: command traefik error: 1 error occurred:
	* failed to open the plugin manifest plugins-local/src/github.com/PascalMinder/geoBlock/.traefik.yml: open plugins-local/src/github.com/PascalMinder/geoBlock/.traefik.yml: no such file or directory
```

**Comment by ezruneko** [comment]
Same error with url in lowercaser
```
2022/07/21 09:24:52 traefik.go:80: command traefik error: 1 error occurred:
	* failed to open the plugin manifest plugins-local/src/github.com/PascalMinder/geoblock/.traefik.yml: open plugins-local/src/github.com/PascalMinder/geoblock/.traefik.yml: no such file or directory
```

**Comment by PascalMinder** [comment]
Did you want to configure it as a local plugin? This would mean you have to manually install all files at the right location.

**Comment by ezruneko** [comment]
i've followed your readme at https://github.com/PascalMinder/geoblock/blob/main/readme.md


but one second to add:

experimental:
  hub: true
  plugins:
    geoblock:
       modulename: github.com/PascalMinder/geoblock
       version: v0.2.3

**Comment by ezruneko** [comment]
Working with the next configuration without localPlugins tag

traefik.yml

```
entryPoints:
    http:
      middlewares:
        - geoblock-plugin@file
experimental:
 plugins:
    geoblock:
      modulename: github.com/PascalMinder/geoblock
      version: v0.2.3
```

http-geoblock.yml 
```
http:
  middlewares:
    geoblock-plugin:
      plugin:
        geoblock:
               ....
```
