### ISSUE TITLE
does not block

### ISSUE THREAD

**Issue by ScreNN** [PascalMinder/geoblock#37]
The plugin began to skip many of the USA and beyond. Is there something wrong with the base?

![notblock](https://github.com/PascalMinder/geoblock/assets/13724242/02b1dfbf-5d85-46e9-befe-44677094227a)

**Comment by PascalMinder** [comment]
I can’t help you without any further information.

**Comment by ScreNN** [comment]
> 

These are some kind of scanners. But shouldn't GeoBlock block them?
![scan](https://github.com/PascalMinder/geoblock/assets/13724242/cf733a07-2788-4e74-af99-c8a6fcf9cae3)

**Comment by PascalMinder** [comment]
Are those HTTP/s requests or tcp/udp requests?

**Comment by ScreNN** [comment]
> 

Traefik shows that these are HTTP (GET, POST) requests. I have UDP closed. I only have port 443 of HTTPS open.

**Comment by ScreNN** [comment]
I think I figured out why these guys aren't banning the plugin. They don't pass the country in headers

![image](https://github.com/PascalMinder/geoblock/assets/13724242/8b5a0d79-4a68-4a5a-a39a-b3cf9d8ad12f)

**Comment by ScreNN** [comment]
I think I figured it out. I should have written a fake router in traefik proxy

```
http:
  routers:
    catchall:
      entryPoints:
        - "https"
      # catchall rule
      rule: "PathPrefix(`/`)"
      service: unavailable
      # lowest possible priority
      # evaluated when no other router is matched
      priority: 1

  services:
    # Service that will always answer a 503 Service Unavailable response
    unavailable:
      loadBalancer:
        servers: {}
```
