### ISSUE TITLE
Error: middleware \"my-GeoBlock@file\" does not exist"

### ISSUE THREAD

**Issue by navilg** [PascalMinder/geoblock#42]
When I setup GeoBlock, It fails with below error. 

```
time="2023-09-02T14:16:10Z" level=error msg="middleware \"my-GeoBlock@file\" does not exist" routerName=webprofile@docker entryPointName=websecure
```

Traefik version: v2.10.4

Static Config (CLI):

```
--experimental.plugins.GeoBlock.moduleName=github.com/PascalMinder/geoblock 
--experimental.plugins.GeoBlock.version=v0.2.6
```

Dynamic configuration:

```
http:
  middlewares:
    my-GeoBlock:
      plugin:
        GeoBlock:
          allowLocalRequests: true
          logLocalRequests: false
          logAllowedRequests: false
          logApiRequests: false
          api: "https://get.geojs.io/v1/ip/country/{ip}"
          apiTimeoutMs: 500
          cacheSize: 25
          forceMonthlyUpdate: true
          allowUnknownCountries: false
          unknownCountryApiResponse: "nil"
          countries:
            - CH
```

Label used in webprofile service:

```
traefik.http.routers.webprofile.middlewares=my-GeoBlock@file
```

Please help
