### ISSUE TITLE
not work with docker + traefik + geoblock

### ISSUE THREAD

**Issue by Vctrsnts** [PascalMinder/geoblock#57]
Hello good.
I have docker with traefik ( 2.11.2 ) and trying to use geoblock and I have it set, in principle if I'm not mistaken in dynamic mode as follows:
`traefik.yml`
```
entryPoints:
  websecure:
    address: ":443"
    http:
      tls:
        certresolver: letsencrypt
      middlewares:
        - myGeoBlock@file

experimental:
  plugins:
    geoBlock:
      moduleName: "github.com/PascalMinder/geoblock"
      version: "v0.2.5"
```
and the `dynamic.yml`:
```
http:
  middlewares:
    myGeoBlock:
      plugin:
        geoBlock:
          silentStartUp: false
          allowLocalRequests: true
          logLocalRequests: false
          logAllowedRequests: true
          logApiRequests: false
          api: "https://get.geojs.io/v1/ip/country/{ip}"
          cacheSize: 15
          forceMonthlyUpdate: true
          allowUnknownCountries: false
          unknownCountryApiResponse: "nil"
          countries:
            - ES
            - US
            - DE
```
But nothing happens. I don't see anything in either the `traefik.log` or the `access.log`.
I do the tests through a VPN that connects to Holland to connect to the VPS where Traefik is located and the IP that reaches Traefik is from Holland, but it allows me to access without any problem and does not block anything.

I'm sure I'm leaving something out, but I can't see it. Where do I have the problem?

Thank you
