### ISSUE TITLE
How to install Traefik Plugin GeoBlock in Kubernetes?

### ISSUE THREAD

**Issue by arsyam** [PascalMinder/GeoBlock#7]
I'm trying to install the GeoBlock plugin, and I have created a middleware .yaml like this :
```
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: my-geoblock
spec:
  plugin:
    GeoBlock:
      allowlocalrequests: true
      api: https://get.geojs.io/v1/ip/country/{ip}
      countries:
       - SG
      loglocalrequests: true
```
 but the error appears: 
`plugin: unknown plugin type: GeoBlock`

<img width="650" alt="Screen Shot 2021-06-30 at 14 31 39" src="https://user-images.githubusercontent.com/31922367/123932821-0374d700-d9bc-11eb-9f12-871f2e153154.png">
<img width="515" alt="Screen Shot 2021-06-30 at 14 38 50" src="https://user-images.githubusercontent.com/31922367/123932830-05d73100-d9bc-11eb-9896-362c45ad2d51.png">
<img width="601" alt="Screen Shot 2021-06-30 at 14 39 45" src="https://user-images.githubusercontent.com/31922367/123932833-07085e00-d9bc-11eb-8270-105e4992877d.png">

Please help.

**Comment by PascalMinder** [comment]
I am not sure about Kubernetes.
In my traefik-config.yaml I got the following:
```
pilot:
  token: "xxxx"
  dashboard: false
experimental:
  plugins:
    GeoBlock:
      moduleName: "github.com/PascalMinder/GeoBlock"
      version: "v0.1.6"
```

And in my dynamic-configuration.yml I got:
```
http:
  middlewares:
    my-GeoBlock:
      plugin:
        GeoBlock:
          allowlocalrequests: true
          api: "https://get.geojs.io/v1/ip/country/{ip}"
          countries:
            - CH
```
