### ISSUE TITLE
Requests blocked still allow access

### ISSUE THREAD

**Issue by beliven-alex-zongaro** [PascalMinder/geoblock#73]
Hello,

I'm having a problem using Geoblock plugin version 0.3.1.

#### **Environment**
- **Traefik Version:** v3.2
- **GeoBlock Plugin Version:** v0.3.1 (Reproduced with v0.3.0)
- **Setup:** Docker with Traefik and GeoBlock configured to allow requests only from Italy.

#### **Expected Behavior**
When requests are made from countries not allowed (e.g., the US), the plugin should return a `403 Forbidden` status and block those requests entirely. The client should not be able to access the page.

#### **Observed Behavior**
While the plugin logs show that requests are being blocked and the client receives a `403 Forbidden` response, the page is still accessible.

#### **Notes**
- The issue doesn't occur with GeoBlock v0.2.8, which blocks access correctly.
- Both v0.3.1 and v0.3.0 produce the same issue, potentially allowing requests despite returning `403 Forbidden`.

---

#### **Dynamic Configuration**
```yaml
http:
  middlewares:
    geoblock:
      plugin:
        geoblock:
          allowLocalRequests: "true"
          allowUnknownCountries: "false"
          api: https://get.geojs.io/v1/ip/country/{ip}
          apiTimeoutMs: "500"
          cacheSize: "15"
          countries:
            - IT # Allow only traffic from Italy
          forceMonthlyUpdate: "true"
          logAllowedRequests: "false"
          logApiRequests: "false"
          logLocalRequests: "false"
          silentStartUp: "true"
          logFilePath: "/var/log/traefik/geoblock.log"
```

#### **Static Configuration**
```yaml
experimental:
  plugins:
    geoblock:
      moduleName: "github.com/PascalMinder/geoblock"
      version: "v0.3.1" (or v0.3.0)
```

#### **Geoblock logs**
```
INFO: GeoBlock: 2025/02/11 09:31:20 geoblock@file: request denied [89.39.106.191] for country [NL]
INFO: GeoBlock: 2025/02/11 09:31:42 geoblock@file: request denied [89.39.106.191] for country [NL]
```

#### **Request + response"
```
curl -i https://example.com
HTTP/1.1 403 Forbidden
Accept-Ranges: bytes
Content-Length: 231
Content-Type: text/html
Date: Tue, 11 Feb 2025 09:54:51 GMT
Etag: "677feff1-e7"
Last-Modified: Thu, 09 Jan 2025 15:49:05 GMT
Server: nginx/1.27.3

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hello World</title>
</head>
<body>
    <h1>Hello, World!</h1>
</body>
</html>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hello World</title>
</head>
<body>
    <h1>Hello, World!</h1>
</body>
</html>
```
The request seems to be sent two times instead of one and is not being blocked despite having error 403.
