### ISSUE TITLE
Having 2 middlewares with same plugin logs all in same file

### ISSUE THREAD

**Issue by lluisd** [PascalMinder/geoblock#79]
I am defining 2 middlewares with 2 distinct log file paths but all logs are saved in the first one. But it creates the empty file of the second middleware.

```yaml
  middlewares:
    geoblock-es:
      plugin:
        geoblock:
          ipGeolocationHttpHeaderField: "cf-ipcountry"
          xForwardedForReverseProxy: true
          silentStartUp: true
          allowLocalRequests: true
          logLocalRequests: false
          logAllowedRequests: true
          logApiRequests: true
          api: "https://get.geojs.io/v1/ip/country/{ip}"
          apiTimeoutMs: 5000                                 # optional
          ignoreAPITimeout: true
          cacheSize: 100
          forceMonthlyUpdate: true
          allowUnknownCountries: false
          unknownCountryApiResponse: "nil"
          addCountryHeader: true
          logFilePath: "/etc/traefik_logs/geoblock-es.log"
          countries:
            - ES

    geoblock-es-ie:
      plugin:
        geoblock:
          ipGeolocationHttpHeaderField: "cf-ipcountry"
          xForwardedForReverseProxy: true
          silentStartUp: true
          allowLocalRequests: true
          logLocalRequests: true
          logAllowedRequests: true
          logApiRequests: true
          api: "https://get.geojs.io/v1/ip/country/{ip}"
          apiTimeoutMs: 5000                                 # optional
          ignoreAPITimeout: true
          cacheSize: 100
          forceMonthlyUpdate: true
          allowUnknownCountries: false
          unknownCountryApiResponse: "nil"
          addCountryHeader: true
          logFilePath: "/etc/traefik_logs/geoblock-ie.log"
          countries:
            - ES
            - IE

```

all my logs go to geoblock-es.log

![Image](https://github.com/user-attachments/assets/f40d7468-d10c-4c54-92cf-d8748812cef4)

and the content mixes both middlewares

![Image](https://github.com/user-attachments/assets/8b7d0018-54e0-46ef-9d9b-0acd12e83b6c)
