### ISSUE TITLE
With geoblock enabled I'm still getting traffic from blocked countries.

### ISSUE THREAD

**Issue by silmarine** [PascalMinder/geoblock#86]
I'm not exactly sure what is going on here, if it's a bug or if I just have something configured incorrectly. I have a traefik middleware chain that (I think?) puts geoblock first then crowdsec second. I am only allowing US and DE in geoblock but my crowdsec is still detecting traffic from many other countries. Following is the relevant config:

treafik.yml plugins:
```
experimental:
  plugins:
    crowdsec-bouncer:
      moduleName: "github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin"
      version: "v1.4.2"
    geoblock:
      moduleName: "github.com/PascalMinder/geoblock"
      version: "v0.3.3"
```

traefik dynamic config middlewares:
```
  middlewares:
    default-ratelimit:
      rateLimit:
        average: 50
        burst: 100
    geoblock:
      plugin:
        geoblock:
          silentStartUp: false
          allowLocalRequests: true
          logLocalRequests: false
          logAllowedRequests: false
          logApiRequests: false
          api: "https://get.geojs.io/v1/ip/country/{ip}"
          apiTimeoutMs: 750
          cacheSize: 25
          forceMonthlyUpdate: true
          allowUnknownCountries: false
          unknownCountryApiResponse: "nil"
          countries:
            - DE
            - US
    crowdsec:
      plugin:
        crowdsec-bouncer:
          enabled: true
          crowdseclapikey: {redacted}
          crowdseclapischeme: http
          crowdseclapihost: crowdsec:8080
          crowdsecMode: stream
    crowdsec-external:
      chain:
        middlewares:
        - geoblock
        - default-ratelimit
        - crowdsec
```

crowdsec decisions list:
```
~$ docker exec crowdsec cscli decisions list
+----------+----------+------------------------------+--------------------------------------------+--------+---------+--------------------------------------------------------------+--------+------------+----------+
|    ID    |  Source  |          Scope:Value         |                   Reason                   | Action | Country |                              AS                              | Events | expiration | Alert ID |
+----------+----------+------------------------------+--------------------------------------------+--------+---------+--------------------------------------------------------------+--------+------------+----------+
| 28683698 | crowdsec | Ip:170.39.217.107            | crowdsecurity/http-admin-interface-probing | ban    | FR      | 34534 Fbw Networks SAS                                       | 5      | 22h43m8s   | 9300     |
| 28683695 | crowdsec | Ip:93.123.109.231            | crowdsecurity/http-probing                 | ban    | BG      | 48090 Techoff Srv Limited                                    | 12     | 22h8m17s   | 9297     |
| 28661626 | crowdsec | Ip:117.83.25.100             | crowdsecurity/thinkphp-cve-2018-20062      | ban    | CN      | 4134 Chinanet                                                | 1      | 20h50m23s  | 9292     |
| 28574232 | crowdsec | Ip:51.195.190.22             | crowdsecurity/http-admin-interface-probing | ban    | FR      | 16276 OVH SAS                                                | 5      | 12h46m41s  | 9275     |
| 28574229 | crowdsec | Ip:150.136.76.116            | crowdsecurity/thinkphp-cve-2018-20062      | ban    | US      | 31898 ORACLE-BMC-31898                                       | 1      | 11h30m11s  | 9272     |
| 28523290 | crowdsec | Ip:93.123.109.228            | crowdsecurity/http-probing                 | ban    | BG      | 48090 Techoff Srv Limited                                    | 11     | 8h21m12s   | 9263     |
| 28523288 | crowdsec | Ip:46.101.111.185            | crowdsecurity/jira_cve-2021-26086          | ban    | DE      | 14061 DIGITALOCEAN-ASN                                       | 1      | 8h21m12s   | 9261     |
| 28523285 | crowdsec | Ip:154.92.109.116            | crowdsecurity/thinkphp-cve-2018-20062      | ban    | HK      | 141356 Universe Action Limited                               | 1      | 8h21m7s    | 9258     |
| 28523279 | crowdsec | Ip:20.65.194.85              | crowdsecurity/CVE-2022-41082               | ban    | US      | 8075 MICROSOFT-CORP-MSN-AS-BLOCK                             | 1      | 8h21m6s    | 9252     |
| 28523278 | crowdsec | Ip:52.165.81.253             | crowdsecurity/http-cve-probing             | ban    | US      | 8075 MICROSOFT-CORP-MSN-AS-BLOCK                             | 1      | 8h21m6s    | 9251     |
| 28523277 | crowdsec | Ip:193.174.89.19             | crowdsecurity/http-probing                 | ban    | DE      | 680 Verein zur Foerderung eines Deutschen Forschungsnetzes   | 11     | 8h21m6s    | 9250     |
| 28523276 | crowdsec | Ip:167.71.149.107            | crowdsecurity/http-probing                 | ban    | US      | 14061 DIGITALOCEAN-ASN                                       | 11     | 8h21m4s    | 9249     |
| 28523275 | crowdsec | Ip:170.39.217.179            | crowdsecurity/http-admin-interface-probing | ban    | FR      | 34534 Fbw Networks SAS                                       | 5      | 8h21m4s    | 9248     |
| 28523271 | crowdsec | Ip:185.254.195.5             | crowdsecurity/http-probing                 | ban    | UA      | 61354 Limited Liability Company De Novo                      | 11     | 8h21m4s    | 9244     |
| 28523270 | crowdsec | Ip:210.113.70.126            | crowdsecurity/thinkphp-cve-2018-20062      | ban    | KR      | 4766 Korea Telecom                                           | 1      | 8h21m2s    | 9243     |
+----------+----------+------------------------------+--------------------------------------------+--------+---------+--------------------------------------------------------------+--------+------------+----------+
34 duplicated entries skipped
```

As you can see in crowdsec there are bans from CN, FR, BG, KR, and HK currently. If I understand treafik config correctly then all traffic from countries that aren't DE/US shouldn't have even gotten to crowdsec but I've been seeing them for over a week since setting up geoblock. Is this something I've done wrong or is it a bug? Thanks!
