### ISSUE TITLE
IP is blocked even though it is in allowedIPs

### ISSUE THREAD

**Issue by brockar** [PascalMinder/geoblock#90]
I am trying to use Traefik on my VPS to expose my services, but I only want to expose them to my country. The problem is that my VPS is in the US, and I don't want to expose all of the US.
Is there any way to do this?
If I add the US to the list of allowed countries, everything works fine, but it does not without it.

(I'm trying to set up Nextcloud with Nextcloud-AIO Docker and can't individually manage the containers)
I leave what I think is important in my configuration, in case I am doing something wrong, it is the first time I use a reverse proxy.

OS: Ubuntu 24.04 aarch64
Traefik 3.4.1
geoblock v0.3.3

`config/dynamic.yml`:
```yml
    ar-only:
      plugin:
        geoblock:
          allowedIPs: 
            - VPS.IP
          countries: 
            - AR
          silentStartUp: false
          allowLocalRequests: true
          logLocalRequests: true
          logAllowedRequests: false
          logApiRequests: false
          api: "https://get.geojs.io/v1/ip/country/{ip}"
          apiTimeoutMs: 500
          cacheSize: 25
          forceMonthlyUpdate: true
          allowUnknownCountries: false
          unknownCountryApiResponse: "nil"
```

`traefik logs`:
```log
traefik  | 2025-06-21T00:11:37Z DBG github.com/traefik/traefik/v3/pkg/server/service/loadbalancer/wrr/wrr.go:173 > Service selected by WRR: http://nextcloud-aio-collabora:9980
traefik  | INFO: GeoBlock: 2025/06/21 00:11:38 ar-only@file: request denied [VPS.IP] for country [US]
```
